OBJS = map.o binary_search.o mon.o player.o rungame.o screen.o heap.o main.o

.PHONY: clean objs dungeon

%.o: %.c
	echo Compiling $<
	gcc -MMD -MF $?.d -c $<

dungeon: $(OBJS) 
	echo Linking $@
	gcc $^ -o $@ -lm -lncurses

clean:
	rm -f dungeon
	rm -f out.txt
	rm -f *.d
	rm -f *.o
